config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "El contacto ha sido creado 😀." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "El contacto ha sido actualizado 😀." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "El contacto ha sido eliminado 🔥." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice:"😵 No estás autorizad@ para realizar esa acción" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :instagrargm, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> No se puede guardar este contacto:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="min-h-screen flex justify-center items-center">
  <div class="absolute w-60 h-60 rounded-xl bg-purple-300 -top-5 -left-16 z-0 transform rotate-45 hidden md:block"></div>
  <div class="absolute w-48 h-48 rounded-xl bg-purple-300 -bottom-6 -right-10 transform rotate-12 hidden md:block"></div>
  <div class="py-12 px-12 bg-white rounded-2xl shadow-xl z-20">
    <div>
      <h1 class="text-3xl font-bold text-center mb-4 cursor-pointer">Datos del contacto</h1>
    </div>
    <div class="space-y-4">
  
      <%= form.label :first_name, class:"hidden" %>
      <%= form.text_field :first_name, class:"block text-sm py-3 px-4 rounded-lg w-full border outline-none", placeholder:"Nombre"  %>
      
      <%= form.label :last_name, class:"hidden" %>
      <%= form.text_field :last_name, class:"block text-sm py-3 px-4 rounded-lg w-full border outline-none", placeholder:"Apellido" %>

      <%= form.label :email, class:"hidden" %>
      <%= form.text_field :email, class:"block text-sm py-3 px-4 rounded-lg w-full border outline-none", placeholder:"Email" %>

      <%= form.label :phone, class:"hidden" %>
      <%= form.text_field :phone, class:"block text-sm py-3 px-4 rounded-lg w-full border outline-none", placeholder:"Teléfono" %>

      <%= form.label :instagrargm, class:"hidden" %>
      <%= form.text_field :instagrargm, class:"block text-sm py-3 px-4 rounded-lg w-full border outline-none", placeholder:"Instagram" %>

      <%= form.number_field :user_id, id: :friend_user_id, class:"block text-sm py-3 px-4 rounded-lg w-full border outline-none", value:current_user.id, type: :hidden %>
    </div>
    <div class="text-center mt-6">
      <%= form.submit class:"py-3 w-64 text-xl text-white bg-purple-400 rounded-2xl" %>
    </div>
    <div class="text-center">
      <%= link_to 'Mostrar', @friend %> |
      <%= link_to 'Volver', friends_path %> 
    </div>

  </div>
  <div class="w-40 h-40 absolute bg-purple-300 rounded-full top-0 right-12 hidden md:block"></div>
  <div class="w-20 h-40 absolute bg-purple-300 rounded-full bottom-20 left-10 transform rotate-45 hidden md:block"></div>
</div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<% if user_signed_in? %>

<h1 class="  text-lg text-center font-bold m-5 tableContainer text-2xl font-bold text-transparent md:text-3xl bg-clip-text bg-gradient-to-r from-indigo-200 via-indigo-500 to-indigo-900 mb-16 text-center"><i class="far fa-bookmark"></i> Mi agenda </h1>
<table class="table rounded-t-lg m-5 w-5/6 mx-auto text-gray-100 bg-gradient-to-r from-indigo-500 to-blue-500 ">
  <tr class="text-left border-b-2 border-indigo-300">
    <th class="px-4 py-7">Nombre</th>
    <th class="px-4 py-7">Email</th>
    <th class="px-4 py-7">Teléfono</th>
    <th class="px-4 py-7">Instagram</th>
    <%
=begin%>
 <th class="px-4 py-7">Id Usuario</th> 
<%
=end%>
    <th class="px-4 py-7 text-center"><i class="fas fa-eye"></i></th>
    <th class="px-4 py-7 text-center"><i class="far fa-edit"></i></th>
    <th class="px-4 py-7 text-center"><i class="far fa-trash-alt"></i></th>
  </tr>

    <% @friends.each do |friend| %>
      <% if friend.user == current_user %>
      <tr class="border-b border-indigo-400">
        <td class="px-4 py-3"> <%= link_to friend.first_name + ' ' + friend.last_name , friend %> </td>
        
        <td class="px-4 py-3"><%= friend.email %></td>
        <td class="px-4 py-3"><%= friend.phone %></td>
        <td class="px-4 py-3"><%= friend.instagrargm %></td>
        <%
=begin%>
 <td class="px-4 py-3 text-center"><%= friend.user_id %></td> 
<%
=end%>
        <td class="px-4 py-3 text-center"><%= link_to 'Mostrar', friend %></td>

        
        <td class="px-4 py-3 text-center"><%= link_to 'Editar', edit_friend_path(friend) %></td>
        <td class="px-4 py-3 text-center"><%= link_to 'Eliminar', friend, method: :delete, data: { confirm: 'Quiéres continuar?' } %></td>
        
      </tr>
    <% end %>

    <% end %>

</table>

<div class=" tableContainer text-2xl font-bold text-transparent md:text-3xl bg-clip-text bg-gradient-to-r from-indigo-200 via-indigo-500 to-indigo-900 mt-9 text-center"><%= link_to 'Crear nuevo contacto', new_friend_path %></div>
<% else %>
<div class="min-h-screen flex flex-col justify-center items-center">
  <div class="absolute w-60 h-60 rounded-xl bg-purple-300 -top-5 -left-16 z-0 transform rotate-45 hidden md:block"></div>
  <div class="absolute w-48 h-48 rounded-xl bg-purple-300 -bottom-6 -right-10 transform rotate-12 hidden md:block"></div>
      <h1 class="sm:text-5xl text-3xl font-extrabold sm:mb-4 text-gray-700">Agenda.Me</h1>
  <section class="w-full flex flex-col">
    <div class="container mx-auto flex flex-row sm:items-center xl:pb-16 xl:px-0 px-4">
      <div class="w-1/2 text-gray flex flex-col">
        <h2 class="sm:text-2xl text-base text-2xl mb-2">App web para tener a tus contactos de manera privada.</h2>
      </div>
        <div class="w-1/2 xl:pt-8 xl:items-center flex justify-end">
          <img class="xl:w-3/5" src="https://image.flaticon.com/icons/png/512/5406/5406665.png" alt="Agenda"/>
        </div>
    </div>
  </section>
<div class="w-40 h-40 absolute bg-purple-300 rounded-full top-0 right-12 hidden md:block"></div>
  <div class="w-20 h-40 absolute bg-purple-300 rounded-full bottom-20 left-10 transform rotate-45 hidden md:block"></div>
</div>
<% end %>

app/views/friends/new.html.erb
<%
=begin%>
 <h1 class="text-lg text-center font-bold m-5">Nuevo contacto</h1> 
<%
=end%>

<%= render 'form', friend: @friend %>

<%= link_to 'volver', friends_path %>

app/views/friends/show.html.erb
<div class="max-w-screen-lg bg-gradient-to-r from-indigo-500 to-blue-500 shadow-2xl rounded-lg mx-auto  py-16 px-10  flex justify-center items-center flex-col">
        <H3 class="text-3xl leading-9 font-bold tracking-tight text-white sm:text-4xl sm:leading-10 ">
        <p class="py-4">
          <strong>Nombre:</strong>
          <%= @friend.first_name %>
        </p>
        <p class="py-4">
          <strong>Apellido:</strong>
          <%= @friend.last_name %>
        </p>

        <p class="py-4">
          <strong>Email:</strong>
          <%= @friend.email %>
        </p>

        <p class="py-4">
          <strong>Teléfono:</strong>
          <%= @friend.phone %>
        </p>

        <p class="py-4">
          <strong>Instagram:</strong>
          <%= @friend.instagrargm %>
        </p>
        </h2>
        <div class="mt-8 flex justify-center">
            <div class="inline-flex shadow">
        <%= link_to 'Editar', edit_friend_path(@friend), class:"border-2 border-blue-500 rounded-lg font-bold text-white px-4 py-3 transition duration-300 ease-in-out hover:bg-indigo-200 hover:text-purple-900 mr-6" %> 
        <%= link_to 'Volver', friends_path , class:"border-2 border-blue-500 rounded-lg font-bold text-white px-4 py-3 transition duration-300 ease-in-out hover:bg-indigo-200 hover:text-purple-900 mr-6" %>
            </div>
        </div>
    </div>

app/views/home/_header.html.erb
<header class="min-w-full md:container md:mx-auto sticky">
		<nav class="bg-white shadow-lg">
			<div class="max-w-6xl mx-auto px-4">
				<div class="flex justify-between">
					<div class="flex space-x-7">
						<div class="flex flex-row items-center">
									<img src="https://repositorio-imagenes.netlify.app/img/logo512.png" alt="Logo" class="h-8 w-8 mr-2">
									<%= link_to "Agenda", root_path, class:"font-semibold text-gray-500 text-lg" %>	
							</div>
							<% if user_signed_in? %>
							<div class="hidden md:flex items-center space-x-1">
								<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class:"py-4 px-2 text-gray-500  border-indigo-500 font-semibold hover:text-indigo-500" %>
							</div>
							<div class="hidden md:flex items-center space-x-1">
								<%= link_to "Perfil", edit_user_registration_path, class:"py-4 px-2 text-gray-500  border-indigo-500 font-semibold hover:text-indigo-500" %>
							</div>


							<% else %>



							<div class="hidden md:flex items-center space-x-1">
								<%= link_to "Registro", new_user_registration_path, class:"py-4 px-2 text-gray-500  border-indigo-500 font-semibold  hover:text-indigo-500 " %>
							</div>
							<div class="hidden md:flex items-center space-x-1">
								<%= link_to "Iniciar sesión", new_user_session_path, class:"py-4 px-2 text-gray-500  border-indigo-500 font-semibold hover:text-indigo-500" %>
							</div>


							<% end %>

					</div>

					<div class="md:hidden flex items-center">
						<button class="outline-none mobile-menu-button">
						<svg class=" w-6 h-6 text-gray-500 hover:text-indigo-500 "
							x-show="!showMenu"
							fill="none"
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							viewBox="0 0 24 24"
							stroke="currentColor"
						>
							<path d="M4 6h16M4 12h16M4 18h16"></path>
						</svg>
					</button>
					</div>
				</div>
			</div>

			<div class="hidden mobile-menu">
				<ul class="">
					<li class="active"><%= link_to "Registro", new_user_registration_path, class:"block text-sm px-2 py-4 text-white bg-indigo-500 font-semibold" %></li>
					<li class="active"><%= link_to "Iniciar sesión", new_user_session_path, class:"block text-sm px-2 py-4 text-white bg-indigo-500 font-semibold" %></li>

				</ul>
			</div>
			<script>
				const btn = document.querySelector("button.mobile-menu-button");
				const menu = document.querySelector(".mobile-menu");

				btn.addEventListener("click", () => {
					menu.classList.toggle("hidden");
				});
			</script>
		</nav>
</header>

app/views/home/index.html.erb
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>
<h1>index</h1>

app/views/layouts/_alerts.html.erb
<div class="flex flex-col space-y-4 min-w-screen h-screen animated fadeIn faster  fixed  left-0 top-0 flex justify-center items-center inset-0 z-50 outline-none focus:outline-none bg-gray-900 ">
<div class="flex flex-col p-8 bg-white shadow-md hover:shodow-lg rounded-2xl absolute">
	<div class="flex items-center justify-between">
		<div class="flex items-center">

			<div class="flex flex-col ml-3">
				<div class="font-medium leading-none"> 
				<%= notice %> <br/>
				<div class="text-center mt-6">
				<button class="py-3 w-64 text-xl text-white bg-purple-400 rounded-2xl">
				<%= link_to "Listo", friends_path, class:"font-semibold text-white text-lg" %>
				</button>
				</div>
				</div>

			</div>
		</div>

	</div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description"
    content="App web Realizada con Ruby on Rails y Tailwind.">
  <meta name="author" content="Santiago L. Pasciullo" />
  <meta name="copyright" content="Santiago L. Pasciullo" />
  <meta property="og:image" content="https://image.flaticon.com/icons/png/512/5406/5406665.png" />
  <link rel="shortcut icon" href="https://image.flaticon.com/icons/png/512/5406/5406665.png" />
 
  <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <title>Agenda.Me</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-gray-100 overscroll-auto md:overscroll-contain lg:overscroll-none overflow-hidden">
  <%= render "home/header", class:"overscroll-auto md:overscroll-contain lg:overscroll-none overflow-hidden"%>
<div class="md:container md:mx-auto">
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
  <%= yield  %>
</div>
</body>
</html>